version: '3.8'
services:
  prometheus:
    image: prom/prometheus
    ports: ["9090:9090"]
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus-data:/prometheus
  cadvisor:
    image: gcr.io/cadvisor/cadvisor:latest
    ports: ["8888:8080"]
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
  node-exporter:
    image: prom/node-exporter
    ports: ["9100:9100"]
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
  java-app:
    image: openjdk:21-jdk-slim
    ports: ["8081:8081"]
    volumes:
      - ./build/libs:/app
    command: ["java", "-jar", "/app/learn2026-0.0.1-SNAPSHOT-boot.jar"]
    depends_on:
      - otel-collector
  otel-collector:
    image: otel/opentelemetry-collector
    ports: ["4317:4317", "4318:4318", "8889:8889"]
    volumes:
      - ./otel-collector-config.yml:/etc/otelcol/config.yaml
volumes:
  prometheus-data: