services:

  ollama:
    image: ollama/ollama:latest
    volumes:
      - ollama_data:/root/.ollama
    ports:
      - "11434:11434"
    healthcheck:
      test: ["CMD", "ollama", "list"]
      interval: 10s
      timeout: 5s
      retries: 30
    networks: [appnet]

volumes:
  pg_data: {}
  minio_data: {}
  ollama_data: {}

networks:
  appnet:
    driver: bridge
