
services:
  keycloak:
    image: quay.io/keycloak/keycloak:25.0.4
    container_name: keycloak
    command: >
      start-dev
      --http-port=8081
      --import-realm
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    ports:
      - "8081:8081"
    volumes:
      - ./keycloak:/opt/keycloak/data/import
