server:
  port: 8080
  forward-headers-strategy: framework
  
spring:
  security:
    oauth2:
      client:
        registration:
          keycloak:
            client-id: democlient
            client-secret: change-me-secret
            scope: openid,profile,email
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
        provider:
          keycloak:
            issuer-uri: "http://localhost:8081/realms/demorealm"
            user-name-attribute: preferred_username
