name: CI to GHCR + GitOps Tag Update

on:
  push:
    branches: [ "main" ]

env:
  REGISTRY: ghcr.io
  IMAGE_NAMESPACE: OWNER   # <--- change
  IMAGE_REPO: REPO         # <--- change
  SHA_TAG: ${{ github.sha }}

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
      id-token: write

    steps:
      - uses: actions/checkout@v4

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build & Push API
        uses: docker/build-push-action@v6
        with:
          context: ./api
          push: true
          tags: |
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAMESPACE }}/${{ env.IMAGE_REPO }}-api:${{ env.SHA_TAG }}
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAMESPACE }}/${{ env.IMAGE_REPO }}-api:dev

      - name: Build & Push WEB
        uses: docker/build-push-action@v6
        with:
          context: ./web
          push: true
          tags: |
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAMESPACE }}/${{ env.IMAGE_REPO }}-web:${{ env.SHA_TAG }}
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAMESPACE }}/${{ env.IMAGE_REPO }}-web:dev

      - name: Install kustomize
        uses: imranismail/setup-kustomize@v2

      - name: Update kustomize image tags (overlay/dev)
        working-directory: k8s/overlays/dev
        run: |
          kustomize edit set image ghcr.io/${{ env.IMAGE_NAMESPACE }}/${{ env.IMAGE_REPO }}-api=ghcr.io/${{ env.IMAGE_NAMESPACE }}/${{ env.IMAGE_REPO }}-api:${{ env.SHA_TAG }}
          kustomize edit set image ghcr.io/${{ env.IMAGE_NAMESPACE }}/${{ env.IMAGE_REPO }}-web=ghcr.io/${{ env.IMAGE_NAMESPACE }}/${{ env.IMAGE_REPO }}-web:${{ env.SHA_TAG }}

      - name: Commit & push tag bump
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add k8s/overlays/dev/kustomization.yaml
          git commit -m "CI: bump image tags to ${SHA_TAG}" || echo "No changes to commit"
          git push || echo "Nothing to push"
