apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-hello-spring
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: hello-spring
  template:
    metadata:
      labels:
        app: hello-spring
    spec:
      containers:
        - name: hello-spring
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 8080