# .github/workflows/pipeline.yml
name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
    tags: [ 'v*.*.*' ]   # e.g., v1.2.3 -> triggers stage/prod path
  pull_request:
    branches: [ main ]

# Reusable variables
env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}   # ghcr.io/owner/repo
  NODE_VERSION: '22'

permissions:
  contents: read
  packages: write  # needed to push to GHCR
  id-token: write  # if you later switch to cloud OIDC deploys

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Lint
        run: |
          ls -lR
          # Or: npx eslint . --max-warnings=0

  build:
    name: Build
    runs-on: ubuntu-latest
    needs: [lint]
    steps:
      - uses: actions/checkout@v4
      - name: Build
        run: ls -lR

  test:
    name: Test
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - uses: actions/checkout@v4

      - name: Run tests
        run: |
          ls -lR
        env:
          JEST_JUNIT_OUTPUT: junit.xml

